# Generated by Django 5.0.2 on 2025-04-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CropSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(choices=[('Summer', 'Summer'), ('Winter', 'Winter'), ('Monsoon', 'Monsoon'), ('Spring', 'Spring'), ('Year-round', 'Year-round')], max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('soil_type', models.CharField(choices=[('Clay', 'Clay'), ('Sandy', 'Sandy'), ('Loamy', 'Loamy'), ('Black', 'Black'), ('Red', 'Red'), ('Alluvial', 'Alluvial'), ('Laterite', 'Laterite')], max_length=50)),
                ('crop_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('planting_method', models.TextField(blank=True, null=True)),
                ('water_requirements', models.CharField(blank=True, max_length=50, null=True)),
                ('growth_duration', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Crop Suggestion',
                'verbose_name_plural': 'Crop Suggestions',
            },
        ),
    ]
