services:
  - type: web
    name: smartkisaan
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd . && python manage.py migrate && python manage.py collectstatic --no-input && gunicorn myproject.wsgi:application
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.11 