# Generated by Django 5.1.4 on 2025-04-15 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_productforrent_image_productforsale_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productforrent',
            name='category',
            field=models.CharField(choices=[('tractor', 'Tractor'), ('seeds', 'Seeds'), ('tools', 'Tools'), ('rotavator', 'Rotavator'), ('threshing machine', 'Threshing Machine'), ('sprinkler system', 'Sprinkler System')], default='tractor', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productforsale',
            name='category',
            field=models.CharField(choices=[('tractor', 'Tractor'), ('seeds', 'Seeds'), ('tools', 'Tools'), ('rotavator', 'Rotavator'), ('threshing machine', 'Threshing Machine'), ('sprinkler system', 'Sprinkler System')], default='tractor', max_length=50),
            preserve_default=False,
        ),
    ]
